const data = {
products:[
    {
        _id:'1',
        name:'Slim Shirt',
        category: 'Shirts',
        image:'/images/th.jpg',
        price:80 ,
        countInStock: 0,
        brand:'Nike',
        rating:4.5,
        numReviews:10,
        description:'high quality product',
    },
    {
        _id:'2',
        name:'pier one Shirt',
        category: 'Shirts',
        image:'/images/11.jpeg',
        price:60 ,
        countInStock: 13,
        brand:'simple',
        rating: 4.0,
        numReviews:10,
        description:'high quality product',
    },
    {
        _id:'3',
        name:'Lacoste Free Shirt',
        category: 'Shirts',
        image:'/images/lacoste.jpg',
        price:120 ,
        countInStock: 8,
        brand:'Lacoste',
        rating: 4.0,
        numReviews:8,
        description:'high quality product',
    },
    {
        _id:'4',
        name:'Coq sport fit pant',
        category: 'Shirts',
        image:'/images/th.jpg',
        price:150 ,
        countInStock: 5,
        brand:'coq sport',
        rating: 3.5,
        numReviews:9,
        description:'high quality product',
    },
    {
        _id:'5',
        name:'Nike Shirt',
        category: 'class',
        image:'/images/11.jpeg',
        price:150 ,
        countInStock: 4,
        brand:'CMR',
        rating: 4.5,
        numReviews:12,
        description:'high quality product',
    },
    {
        _id:'6',
        name:'shirt',
        category: 'eye Glass',
        image:'/images/11.jpeg',
        price:150 ,
        countInStock: 4,
        brand:'nike',
        rating: 4.5,
        numReviews:12,
        description:'high quality product',
    },
    ],
};
export default data;